import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bunachat",
  description: "Generated by create next app",
};

import { AppProviders } from "@/components/providers/app-provider";
import { SocketStatus } from "@/components/shared/socket-status";
import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <div className="size-full bg-[#F5F9F9]">{children}</div>
          <SocketStatus />
          <Toaster />
        </AppProviders>
      </body>
    </html>
  );
}
